/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TextMaskingComponent {
    }
}
declare global {
    interface HTMLTextMaskingComponentElement extends Components.TextMaskingComponent, HTMLStencilElement {
    }
    var HTMLTextMaskingComponentElement: {
        prototype: HTMLTextMaskingComponentElement;
        new (): HTMLTextMaskingComponentElement;
    };
    interface HTMLElementTagNameMap {
        "text-masking-component": HTMLTextMaskingComponentElement;
    }
}
declare namespace LocalJSX {
    interface TextMaskingComponent {
    }
    interface IntrinsicElements {
        "text-masking-component": TextMaskingComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "text-masking-component": LocalJSX.TextMaskingComponent & JSXBase.HTMLAttributes<HTMLTextMaskingComponentElement>;
        }
    }
}
